kind: ENC[AES256_GCM,data:OYspwtk6,iv:UwaT9J5WOVGC2mt0T9XpASYZtX5e1hKN52uEMwXPIf4=,tag:EVcg3dR2rbfR5QviFiqOGA==,type:str]
ansible_user: ENC[AES256_GCM,data:EHJhqn0TY4a4,iv:40WA0EJ3FZdEeZ7Kf+LsxK8JPwM1LWk551veHOKfZSs=,tag:8FsKyuvCsYcBzTkvY0T3Wg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8lfw0ergSpyXn+U=,iv:nl/v/uex2VWTeOkMOZ8GYF9eS2Oo8sI9AYTOqAJ/kUA=,tag:WZB0uN13/Lit/3/1Sgc+Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT25sSU9QRTlNVUcrVDRy
            bnRUZ1hoNnQ0d2Q3aktycHlZSWJ6aWd2UzFNClF3cDJQS2dvMG1lc1U0V3hodFc5
            QTh4OGp5VmxvbGxiOWdwVi81NmlhVWsKLS0tIDZrdEVuTzFEZWJKcEZ2aW1Vb3lG
            elFyRjZ5aEkwT3RkVFhDbkM2eEtEZE0KR1Ts9sLloP7NFA7/AafI0SAVqpEjyV2V
            O+BZhhMXU6+ooumQ7utMoZuBr2exA5GXbmAYaKDPNrmoV1Kpct484Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T01:38:47Z"
    mac: ENC[AES256_GCM,data:fQOE7ybsUfpRiBTVpYxioGAiKz3WIGe2jfxsQYcFutM8I+IhGWoqXOnFAMQ940RhQUuujtHjfOTz3EyTekKMtkp/AikY5G5yLiXa9ODxjmE9tuziHGRxtfR5wpqQMgWV8yIJuVKFEr4OhxgrYwUvQEHJvXvtfFvPmxXcYJkm7Q0=,iv:sTZFnUaZjBYQoYZzSbNijKOTlb/ztHvDxJcwRPQF/d0=,tag:Ncps336QT+EmEF7umrvl9w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
