kind: ENC[AES256_GCM,data:Amxt7GUS,iv:S7ZrJ4ETfxcZblXxc+sMP5tF3qXKbVOhhi9INNMZ0QQ=,tag:adkqUYWLCVI13Q971005TA==,type:str]
ansible_user: ENC[AES256_GCM,data:Y77zd8QWTI1x,iv:lMGF4z79MxSebFmP5owVhxyaGLSA3Y+QoN/vMG5pqug=,tag:lWCAgTxlaXwo7XPK568O2g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:R7zPCm69Dkc0lIo=,iv:jwAgWMQUynUMo5sd9Lyc2090YwjMQ1z3s8jySFEJycU=,tag:Km1EEJkmy0xZZxfv6SIfVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQ1YydUdJV0l0RERxZnI0
            MnpJVFduUGdDMWh5SUVVSXhwUnRybm9uSEhzCmVyV2JWOHlIYk53MW9YS2M3WTM2
            bS9iWWVjYlJsNU8wZVJUaUREbkFYZmMKLS0tIHd6R0FOYk9XS3BzSmFDUS9pM2dB
            c1pJVmNlNms0ZXJSbTFpOW8wcWN4NmcK1+0cenl5lsLV40HJxpTWaQ+78wu5UGON
            lZR21Zbbtr6GhejhNswApuATycLda38J73apB58Ye/y6Z/KM93sWWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T00:25:58Z"
    mac: ENC[AES256_GCM,data:iZFx2Jb0H1r3WxZBVGUWPO1QtpLFac1km7L64gKhoJ0hHLIZ/1IaJn/qM6VVF/xk+DmSdLLWLg8Z4nOxh2SMJQCQ5dYsJ5SLGmhxzT/0wPmWdlaVZOLp5dPjOsfhCNQ+GLYKXeUh1MDKOWOkxEnEE5tcPl/2fTOTs/SR4Zh0EL0=,iv:aQm5I+p6dEQ4hiI/QP5U1bL1xa0jKdkQT2BhkM4VQTk=,tag:+5ALYIbp0GtE/MYjL/mggA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
