kind: ENC[AES256_GCM,data:MKqtCSeU,iv:FSAsPd+1PH/q6udc54EdU3EbmdLW4R+QIsjYFnL6FCI=,tag:nylYtKidRKGgZbLb/wtPYg==,type:str]
ansible_user: ENC[AES256_GCM,data:D2jYCY3457QB,iv:sDEGu7prcz2ugZoDpZXJv46U16yXBLQwl84G1On+D04=,tag:A+zOTNbZLxaGjE5vceCS+A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:sM3NOA3MY2qGxxE=,iv:eOzu5PP4weQh1mjJJk81zoppiltWPZCkfZkIDqHGQs0=,tag:KfIWidnN/ryYVL/c8uJ20w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkblNUL3U4djZDZTdvQjdG
            NW56UmpGbWRHYXNXbWRzUTNoTTlZQVI0RkVJCmRRMlYrOUtMdlpKQkpXMnlMSjVp
            Y0VUd0FwbFh4TzRCZXpYVDhwVVowd2MKLS0tIC9WUEt4WU11bWl6RFhtN3R2eDVv
            VU9SWU90Z3JrZmxraXZXTzRRZzJEWTQKJw4uoJblx68LSe0fPK6X80Xi26q1Kx9Z
            qdZQq8OGY4AwNEyd2GOnN8+boSiDbIQLTyt13uIPXGDXYf8b7asuSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T01:38:47Z"
    mac: ENC[AES256_GCM,data:2Sb+M7co19EZebYR6GDGVwY9LigmPyZ78Nb3PwDdE8dQHg3DjRbq3XmozAXRWM7jbQsm8KJ3fUrCC1Gtg4798fqy3D9czP4S6aDN57+d3xBIeu5D2Fhy2XtROn/D38v4rgMMaJoaJTFl6xapHVYQuqvfB99a5xMPszu9U57ZK3A=,iv:DdvWLU+sxsSidKD9azhtnpoww8wXbPKbtXPfMTaloRw=,tag:5KgIQFGmbkUPdUggQCpbAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
