kind: ENC[AES256_GCM,data:N2ZzfxAU,iv:LKbpLVP1EA1+XqoqRL8RJRPBxErWqdEsu/zTbUojTTA=,tag:PBnBlmmZaNLE/8ZU+P1eWA==,type:str]
ansible_user: ENC[AES256_GCM,data:4hkWlI2MFySp,iv:lcgf5aVIYmU6HhES1xbeUTwyDaXnjJ8Lg81VTy8IosA=,tag:3WBuh6hs48fldxSot6ag5g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:bgmYcVOVan1YOGs=,iv:zRhRoiqZrizPwOdcIWEHjyKP1vTiOvkUz+bCmYiAoUc=,tag:3wYpZGdUFTLSo4dV++otGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNUVHekNXaUloR1JhVURx
            bjMyYkg2a1FwMVNrWDQ5enhUWEZiYkVMTHlZCklDR2kvbUhjRGN6dXNGc2UzOUZF
            RXVkWVR4T3ZLS281STdsakwyNjRrbG8KLS0tIFgyU01kRHBHR2lUa2NBMFpTN0tD
            eThuNE9kSDBmUU5oQ25RV3FLR3R3QmcKHGQZjfzRcB2kxetH2FzcRqbpmtY/z/ak
            iT5cKAEEJkFdbs6ixkRy+1QMB5s21vqF8aLMfraSDonOrWd99S3Ngw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T00:25:58Z"
    mac: ENC[AES256_GCM,data:YsXElTDn9YTYn2laiouRqYVhS4rdwaO20HyF/UgmPnHwqECOOBYaBXUKRJUK8h7+m9iLxwJIVf428yVPidrOswBvPfoz/BJXG83raEffhm8cdxyEdPtZYDTtmqas1INt3Owj+6V00z9Hevlms9kusedcUq6pC++KlYs3Ir0sp20=,iv:+IG4FJGoM++PSJ03qps1HiWNFbffc3eJLuRglRU8zOE=,tag:m5G4Brss/5B3l8ipySCrBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
