---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.8
    path: /mnt/AuxPool/nextcloud-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
