---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NFS_SERVER}"
    path: /mnt/AuxPool/csi-driver-nfs/nextcloud
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: storage
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-apps
  resources:
    requests:
      storage: 5Gi
