apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    nextcloud-username: ENC[AES256_GCM,data:LtfZjHaNH0ya,iv:vewlivyv+62WFrCLxh3CzDo5tOiM0AT1/ldF3c9yMHU=,tag:M0QYyw2AC6zwqQSvFz2cuQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:Al/EjoQC45C17gHYJx2PtHmCTAJAjslcT+pt5hhpV/g=,iv:U0t76feaZoe/Z/nTSIeA4/nC1S4vv4f0X0ivDAxSpYY=,tag:VO+bEKU9oAadif9tA6RYfg==,type:str]
    nextcloud-database: ENC[AES256_GCM,data:SuzR94v/z2wb,iv:azST0jIhVhhsU6HCKMgLAgjPz3erhX34Uz3bBhmmDE8=,tag:MC6ZawpR0C+kD9jJL42zDQ==,type:str]
    database-username: ENC[AES256_GCM,data:wk/fdtwpmVg6,iv:tkPNON+IrMcG30nXNATmHmkaAXLfKgs/antKTzJnkjA=,tag:hWGb8/CMIP+V2upWj4fQ7Q==,type:str]
    database-password: ENC[AES256_GCM,data:gr+3ZCECfis0+sNixYOJJrtC54+P7OdeDszXRTzRgjo=,iv:mR+ISIItwuh073yeRQRGPA5A/XEwCZMSSkXLLkqTxfw=,tag:OF2bWjfMkpqFQoy9ZrQHwQ==,type:str]
    smtp-username: ""
    smtp-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeWY0RFJNQk1GTmUxWXE3
            N25NUWVuTUppMXN4ekpVdFpKV1lPQy9SVWpvCjZld2JzbG9Td2NacXV2a1dXd0V5
            Y3p6Q3dlYzI1WkpZa0paZFFjS2I1TFUKLS0tIGtESWhmRTkyNm1CZ0xIZzNMTjNL
            Nm15Z3ZUK2dvbFZROUdYUWtnYVY0ZVEKSkF9XYcpTi78af6OTHrD77AOko4cRFM5
            XsnNLeUVTSJZ0E57jG2cg/fGzR8AyD9N1t4RFH/QGIOovAzpFGM9LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-22T17:37:46Z"
    mac: ENC[AES256_GCM,data:uyqWEyI7k1vA/lACV41xlID58DNBKQg8V8+ZHQeK0wY/nGTN8kAGJkS1EzzLQccpIqBWjUwIrSEzcqBbyu3LtIRrRXm7uXCc09wTi0vcO2p19amAv0YCQU2u7tl3+En4kb0xuGzreSJj+GvbmvzcwcNXp2nrugnBre4WE1Dwt8k=,iv:1xd5ABCDiSJrr5SJAzy2AHF4aJkbjGTXjG9A1r60Hbk=,tag:Y0bHNS2NTPROFHaN6/KLqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
