apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:ACApxs4=,iv:2Z5zEwjriKqZkBcamkloMLghu1yHKAOgzBmRacfTbWI=,tag:X5bPccaEYtpDAg3qf8x7ig==,type:str]
    admin-password: ENC[AES256_GCM,data:zkA6+uapZG1rrjm4PTZVc00+y1Itijgr,iv:fwjofuI1maD/joLPCoST7chkAc9anoDbq/MACStCR80=,tag:o0VLsX5ryvTXr6cb6I1+XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZDU1dG95eDR1bmdEZnB3
            RFpxRUY2Q2xPVHJRTmxIZzVaZUcwUnFwQm5RCk9OVEc5SVR6T1JpSDNxRUhXM0ZL
            NkJtVzBkK3pOWEtJejFianBCQm5aNVEKLS0tIC9jYWZ2Y1RlazBGTkpUNW01d04x
            S2l4aG5EeTg1cW43RWhOVkkrYVBJeGMKZf1UiMWY1f4kk4SGMdjid9pQGU8O08Fl
            58qpVrOfzgAd35cUT1VtMZH8n43a5AazVs59ngULAvy9m5i3FgdfNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T01:38:48Z"
    mac: ENC[AES256_GCM,data:a28RTv/mqkRR9KSPxLPZ4czHW8FIV9ArtYJKGbT9XejpazIjEhej6gJP0tZHDIPyi+ff2+jlRkM3b0ruT4LnWlGdfZAeHsg+U3Why25NW4LL+FQcpyb/8FXetvuyMYY99K4jGRZQwvVpzH4ssUBew2TPVMwddDR777PbxJv/9tM=,iv:zqdg6hhZCf2Yxay+cVA8MWbILf1fO6dQjsO7Aqa8/MI=,tag:9H9pcIhPhTZMCehqCYZAxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
