---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: test
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/sleep", "1d"]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: automation-nfs
          mountPath: /mnt/autmation
  restartPolicy: Always
  volumes:
    - name: automation-nfs
      nfs:
        server: 10.0.0.8
        path: /mnt/AuxPool/automation
