apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:X0Xwz6UU8F5nXGrX556q7jSdlfr9lXBqiJI9s6qWPA1KWDqyIg==,iv:sL1vt8hnNLbhxDpCJ6mX95WTYovDfW1qGhSK1X8fdcI=,tag:9/cDAplkUE2njAS9Lyd+JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MkpNblZiUVhIVWZ2VCtp
            V2pLZmpHMG52VURKRFc3V2NhcnkxaklNblNFClNrVU0yMUxIL3U4MG1IZ1N6Yk0y
            QXlwcGdJUTg4MnpQUjhJMU01YkRHQ00KLS0tIDJrN1RXMmVZam5GWk1lU1BZK1VB
            YURQeU5kL3FYS21JV0NoSWg1SDBsWjAK9XL1HNWV6ElVvsaz5V5+p0EKYj4qXO8B
            mI3h2clUPUnR6MEEjE0LGO0hro9rYtUoqP1OpYgzwd5/ZETRF80sSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T14:50:25Z"
    mac: ENC[AES256_GCM,data:ikJoU8FVndu35Mb0HHXNJWvmoihlRgqnYao0zkJL0Xm7V0/m0OzeGuuX0kYI1Tifuanoqa5m0oOgCuVBjoKLYu529WY7DtwSu8giIKwWxh0dj6tuehAMvnXVCh90hLpz6B4ZQE5DKQgB2xL0T9OCbcHmjaZ9D/Bu8PA66xdo3PY=,iv:OvtanrMOFXZTpNhBmqkQPb4KOxFkrxaGo1RW88aRums=,tag:8Ougo+hkL4S6FwgepQwD5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
