apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:WnDW1QzKWa/byB3Zyvu5WUkwiHaibiLVKNk=,iv:Fe5TmOgIrJqsO83Fm/EbA4m7AkfXLA3Y3B9y4ns/mJ4=,tag:xqku1/gum1zC1Bxv26p2lA==,type:str]
    api-key: ENC[AES256_GCM,data:5xbdGZf0eTe2WxmOdpV3WgABPHQevjBGqOVK5SRUHf3KEjfRO4AwUA==,iv:lgXmRwuoQU8QgV3XbRFFP9mqiaQwkiVXzDpHHKKXkOw=,tag:NsMPhyTHQnzmi5nNh+N9/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQU85clZpQllwN3M3LzFR
            K3oremRRREdxMHFoZVNJMUttcHlLWG1BREdrCnphNFhyTDd2eVZDYXNPZ1crejZp
            OVZueGdRMzFHZllzbnBGcnFoaGVWaDgKLS0tIE4rNFQ4ZDBFWUVZK0o1YjRvWFVU
            OGxBdnhPdWxnSWpFZWRaSm0yblhacVUKngLeOKjuDGBOZkeuSyETmiXr5nmFFCSX
            cKjH32RqY0fHiU7iJvMATWGLJNA/qaILshV1A/BhnAlCbUfhay1DQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T00:25:58Z"
    mac: ENC[AES256_GCM,data:ovrNCxqpXQtevbLSiLQ67u8o2PsqLSBsyG6xx8MVkAh7r+LF3InEAyDvN6hdiTrQeK21UPmMq7DHLTZ+Pf2d+tdR5Ue68iuoKoutY+G4flLtRHtLdN9Kd/FoXcUjXlDN+UoIWbdcSyB+bS6I9aoOlC7lAvdBOgDRkjZz9lxlMdY=,iv:vgRLuB3PSetJOnMO2JBswfqFblPGun/ZlZrgdyg7Hdg=,tag:nhdg7CDcglpQKHlsqA7YFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
