apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:y/38c703joR3/FtHk5g/o+6uo3xzuPP8voI=,iv:gKwJOvuXMVmimMgTQx/S2XWUQoqOzzYir0amLjOGQoU=,tag:862Z1ttqytcMWqCCA9qQRg==,type:str]
    api-key: ENC[AES256_GCM,data:IOKPVDF2Ad1aHDy3bk47Qr/wSVj8Y6G2ev8wwv46AQVgeiNwKw==,iv:VqJISWOyg8WeeLgf7FpuSbsYbZj+p/F0dpHf60j0ycQ=,tag:wvhJ5ZSLkWuW33b6i+ewwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVDZkcWtHcWdILzZZd3hh
            RE0rM0VIUkxzYkxjVnRuYXdQNUFoWXlSWDNvCm0yRytPUzU4Y1JhMlVoVVZwMzdz
            NS8yVHBrdzRadzlhMnI2eFJqQkdYV2cKLS0tIGxhRGNnWGhrRC9WdXBlSmp3V1Bp
            MElyWndLNnZ4bE81YmQ4cGt1MDJvaDgK9LpBfJxxm2mJXmUTBctc8DXvQ4vak2FT
            4KKTWFOXBiYem64T9SwhHTlcOBk3FA2fbKmrtw2KrIuYkrvJPFHKug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T01:38:47Z"
    mac: ENC[AES256_GCM,data:GLjApfMcxllZKLiQyL3L8pfZyn/LYoE9LzTAUSCKot8ebSaHjgPnNejwse3jcd+aVo0m5F57I4BMbpsZSClRoZQOy2wKjuULNwLv8mQz1Z1O5v3OToTJZMY+LomkrTkwcnbQ9RbiKNhkleKGKLAUDA7LZSGY0hnfSmmnguX8/Cw=,iv:MCnnGanXP1uExn1P5M70s6KkQnroG9HjTmxZ/PmPoKQ=,tag:8fOlMHZU3xrkBQRE07Tk1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
