---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podgrab-config-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name podgrab
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-apps
  resources:
    requests:
      storage: 5Gi
