apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    nextcloud-username: ENC[AES256_GCM,data:LtfZjHaNH0ya,iv:vewlivyv+62WFrCLxh3CzDo5tOiM0AT1/ldF3c9yMHU=,tag:M0QYyw2AC6zwqQSvFz2cuQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:Al/EjoQC45C17gHYJx2PtHmCTAJAjslcT+pt5hhpV/g=,iv:U0t76feaZoe/Z/nTSIeA4/nC1S4vv4f0X0ivDAxSpYY=,tag:VO+bEKU9oAadif9tA6RYfg==,type:str]
    nextcloud-database: ENC[AES256_GCM,data:SuzR94v/z2wb,iv:azST0jIhVhhsU6HCKMgLAgjPz3erhX34Uz3bBhmmDE8=,tag:MC6ZawpR0C+kD9jJL42zDQ==,type:str]
    database-username: ENC[AES256_GCM,data:wk/fdtwpmVg6,iv:tkPNON+IrMcG30nXNATmHmkaAXLfKgs/antKTzJnkjA=,tag:hWGb8/CMIP+V2upWj4fQ7Q==,type:str]
    database-password: ENC[AES256_GCM,data:gr+3ZCECfis0+sNixYOJJrtC54+P7OdeDszXRTzRgjo=,iv:mR+ISIItwuh073yeRQRGPA5A/XEwCZMSSkXLLkqTxfw=,tag:OF2bWjfMkpqFQoy9ZrQHwQ==,type:str]
    smtp-server: ENC[AES256_GCM,data:srQyDyMEHhkLwZuRbJ4fioMX,iv:jTcnjWZbltR9rwW5BAYywS2oy5yvcd8+22LgMsZ2yNA=,tag:ug84MSJtFsfRHusYLnGmEQ==,type:str]
    smtp-port: ENC[AES256_GCM,data:+Do0,iv:lqj7VDzJGYk7VJ8A76BgS7jYjxFkIxIlyS9Fmwv6oBQ=,tag:F6yKP3HHF+g9m1oFEIIGYw==,type:str]
    smtp-username: ENC[AES256_GCM,data:vuRSIjQU2zi2LFKiRIcReH9v8QqwB/BZ,iv:+YLJCQ1n+ils2B3vNs/hRnltoqKEAe/wdfrjv8aziQA=,tag:L6S4aFhMijmVKWy8KT2fgQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:mC3F929DmV9WG8ThlaYpQ2itinWabiJo6r6OIpDdH4Q=,iv:KLDN3x7O23JEdi5Jk2ywuXB0FSgs+vq4zex99LKN5jU=,tag:NnhY6o6kGzpYPbF1aOQ/CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeWY0RFJNQk1GTmUxWXE3
            N25NUWVuTUppMXN4ekpVdFpKV1lPQy9SVWpvCjZld2JzbG9Td2NacXV2a1dXd0V5
            Y3p6Q3dlYzI1WkpZa0paZFFjS2I1TFUKLS0tIGtESWhmRTkyNm1CZ0xIZzNMTjNL
            Nm15Z3ZUK2dvbFZROUdYUWtnYVY0ZVEKSkF9XYcpTi78af6OTHrD77AOko4cRFM5
            XsnNLeUVTSJZ0E57jG2cg/fGzR8AyD9N1t4RFH/QGIOovAzpFGM9LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T01:43:37Z"
    mac: ENC[AES256_GCM,data:9ayh1VTprYf5TBFBhO5O0DZX2vVwCcrNMuec8kGb9DcVt8HSkeWwXv/hU9b9/xyynoK1wHnsHCrdLe/Z6TcEJkMsXUH+kIcUDCoq277eyTTeNz5J1FnSN/YR3qfg6I3ziaVyBQ32TIof63kdjfwoL2B2zP5u0jlwdJ+ql4IVTXM=,iv:BAnt0lXHtnzLOQaDXrymR+tCiemneULr2VdnvK1I+68=,tag:ykkWIVXAsxl5bssWon9qSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
