apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:A5KGOStRE8f4SknN9JZVv5pyUjCGW0p7Srb3DaQJZeENR27uJbZKlCC70J1e3uepwiWx9PS4K1qwjccn,iv:RkFaxjNfn1HP8nVrkMZISXUGO1bwlYBjIR/XzKEmCVM=,tag:oHA7tZoW209iceX8VSQlmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdGYyUThJVCtZTEc3OW1v
            VXEzRzFSUmxIcGtvZS9ldGdrMkt3a1V2bVNjCjAweWFUeldaaiszSVVJczV2dzhE
            ei9vNkNpSm9iUHB3YmExY2pKYTg2QWcKLS0tIENyZEc3UTBUbG9zbzhZUTVJREpR
            dWRRL0pjNFgwQTJYdmhOcFo1MDREU2MK5+fAy0ec2FZSxNWT3WJQzN3S68spbur1
            Xyix+hK3gnrKwv+c69QSbcaM5a7i27gt9U74dtqTOqowGnIaXnxOYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T02:00:27Z"
    mac: ENC[AES256_GCM,data:sebfz++638B6Sf+I93PqHMJTqXOw0q2bxRGgySY85bep6SFHa2k8zI4dqClPOnE0ehHaV7XrmXlToa2aHQIn437sCZU/WHD3b8tu6lypH2DMpdtEXiSd51sNunPZyPOuyj1KfKAbgAP8cQSs3BqTAg2d9q94zkaA5Mgf7Fvrgpg=,iv:RXIKrg2IQsx67FYaM4pVDF+WWJrAf+kcfgNOyNX2tP0=,tag:gJAzU6BCPNFJ0Ael+PMAYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
