apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:NUy9OyffTf5dwfv47B58AR5U2DudKUJ+NZj8JZqDFB+jC75rCxoTQChi8vM5p3zjNc9e8VJOB6Yf27xT,iv:ZyayWmtWdq1o0Dct+RdWlwYKWV0vs3Zt88Qlvy1A/eI=,tag:OFT/qM+pLEPgrPV8mvX+Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOXRKWDJkWkhhRmJJc1NN
            dDJXRmFEQzhqYmo3WHVBdVhTOXdIaGxsUWpBClgrL3QyWktBa1V4VUdJSTdpWlEy
            Uk40OGxTYm9yM1ZrVmNHa1hZQ2RpYTgKLS0tIEdKOEJwOER6dnhGRm1ma0pNOCt0
            ZHNpZFQ2b0Nna1NPdjB3TGpPdHAvY1EKFWjRtSzWb06btfZVBP6m33uCN6WmZVD5
            FFgefTSMi+SjMPSl/jhUahfn/C50I+Q3UF03IvIbhgk8qxj6TEEc6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T01:38:48Z"
    mac: ENC[AES256_GCM,data:IwPswUXuPo6eeG4Y7/QPavPfa0NOs4zdvTskczDB4hLuTzsorrnhy8OaHDO6XpfA45DGHkXtS/wujdmiF7pnIpHHQn4Ech4fs5hYcJ2T/qAVTmfbHDkiwWJtV0mxVS3RtOof8mCHzXXenP5T4k23Zq5zhFgPm4jzjvlFzWwqnA0=,iv:WTU3n9TFEE00wB0wBOP47BG8TWZyAcyXSNmeHQX56QY=,tag:sWE3NQIzUuS5MyyklNGOAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
