apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:iPLDWOkIgaqIW+Yy/v9X3a0RBrcmW664PTQWgRK8PtBZoarZU2VMC6IscxWSw4jZ60kddhQ/142o4twQ,iv:m8IcmmlRQByQNU7rmig9uSwtq0R3MNW9tJhBXxqFSGk=,tag:t+cU2vRfka/QSCqGhcrFRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNndFTSt5eFRUdXh6QmRX
            eVV1Nmtad0d6K1J6MG45aUNJVkpPeEdmYmxBCnRLNkdEdVoxNzdmWDNQVXRwaHFi
            eldxNndZNW1ueHJFa0kwbUVEL0t4TlEKLS0tIDNLRW83R0dIRFNGQVI0bzU3empP
            OVBzei9NYnJ6VFhyWndEb1NEbkVzOE0KFAZw8ifrxmbvdJeBQefBIX1E2XBOymPe
            aoUZYEP01XfuxzYiHRgedpTivPuTMTo8I5e6UZsrCyhAedxsloFMFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T00:25:59Z"
    mac: ENC[AES256_GCM,data:unoAcN4RUDSiniDTzrHJxDEVKiCSQqs9xlMOTHfFi2hGBC8ziZBnx16Reh4dNpPTf4SfXAUy7AS18WXCaMJg0OlAY6S3TomX7FGVlgYJvEzukKK2TxivgBSaFPTQI1D+gpp7IK/Wkr0B/ZHENxtwCoghidZzN83EVe8LjDaq4cI=,iv:35lVdYp0Q2lVfgccqeLnmFLR/4LqkUKRkeLfFDOwGgU=,tag:PvxK/I+79wnKTOSlc3cYnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
