apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:h8j1r+qiggtr0ZkHt1lkQH+BXrWdiVhXRCRcP5zA8pTRfPKOzZqPizEemP/M21fjogGNtRZvrvU12b2q,iv:ElGZaaasCchEwkYf59x5IF2SjOz8K1bUyMgbVBANeNo=,tag:wIEyQE+95HDEh4RAT4+mHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZFhkanF1NzNXZ3ZMbVFO
            TWd6V3o5QXoxeDBYSXlNN3BXU1RMdytLL2lZCi9vNElSZ050Q1kza3RST3hWV1N0
            MXBsSE05WU9rODNGTHhrWXhDWVE2Z0UKLS0tIDdnNTJ1WGxrN1U3ektSUlE2WFZV
            K2Y3bFY0Z0ZtRmlLWS9ZeENNbVNXb3MKQJysSBwcphq2bEUyBK/xVkwKnRZgX9p1
            fbY9gsJJoKtmCnQIN7cceq9XZxgQBZOKY2GvQ/U3z8Lhtx0JC9AG8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T15:16:03Z"
    mac: ENC[AES256_GCM,data:YlHXIm1mURsnw92EaxY/QKYs9lIj3VOOCfY79EU5faQnQbJK1DOC9BCCacGj2RL6TrjKv9ScDmn0aTNychIHHZyqYGz6V8zTGRloX7aqi41d8zMjHmBNZ1t2uy/G8nhG/8c9D+iUA65rDvC2TDgGP/2pJ1Ky74IpUnKGBUdsJ9o=,iv:4g7uKoaYV00p7kr9LLCRaOVs1plnPVuVuKZbp0fpBaE=,tag:gD8ppBhvx1+nilwLedn+wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
