apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:2H1rY7wDMswbDe+Y+wkLh9tU1K6njxmU+L6O9VTeUlheN/QvvglKPFH285ktTrRUdFUcLkLkgw/Z/xEO,iv:+rvstkIkPXM/AtCAVDPLMLfWRWvaKgmhaHrEZy+Fo+8=,tag:pHePBlv412oM9auIYj4lyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZzFlc0N6KzJ1K1hsSzJ5
            Zis1OWR5WmlkUUV5cU5zM2lSci9URVRzVVhJCnMzUnRMcG9LdjZRTDEwS241a2xn
            elhITDdJZG5nUDlxRndTWU5JSitxdDQKLS0tIERWSU5nemkxbEtBWFZ2VkZLS1pm
            bm9aNkFQbVZTTUJxQklUa2xWUzB6UEUKJ2U5sv80hwoumZU34NPvsdjdYFbKVU7w
            Kls+uZJIYzVWUmhxJgJQfSxHkRVROdHx5O6xJWnKm//3Vp++IKQaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T14:50:26Z"
    mac: ENC[AES256_GCM,data:4F0tbBd0XGNf0W+SIlLhcOQrRjSyWxuNGdieP807/C6GDG7f7apiLHA/M55Hh/2x5b0JyDiNJX1EUKySImsOpbMx+TZzxhz6tVwcgfyaQEBv11rTOFmh2+ADeLdfZjspNKvsgNaJ0kuyM5lCJ6lMk/XK228rXCG/D/qVOAqLe6w=,iv:mVOuzm25IVLDOdIy3FKq0ckRE9hFshbBQKgyUaVuQKg=,tag:yfRhf0bU49ecih11SfwxDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
