apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:TfbI51ZN6U2js1E2QA==,iv:HGgRLFyZLHiLhEdZmbpnDozmQwGu6L3MsV/5l0CltbI=,tag:z8to2M3VdxvUUQ0VqFj0wg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aVG2kJ8YRbANQZN714BNbpx2VzKPag7ao9w=,iv:ax0A5BMlEdrEtd0Xc0GYrRPCjsZGZV23sKd4Mn5G3uI=,tag:yCQe0DzLSItpIpj58EESvA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nLeEk8o2hAYNBsN86QTYfuHoOceHzjvpTLlfXXO1BvU5UbXR,iv:+UC9e5+vl8GN6NcI1Qf6ya/C3cZqTuxassH+4tEmyLw=,tag:S0KCV8oyqGO8Cchp6EdHfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWelhWQU94YVVWZSt2ZjRs
            TTBSUHExSlprOFRFcVh5T0hBZU5EQmV2UTFZCmNTV1RwSEpnWVVGd3N3RDNMZFpl
            L2VONXJzWTJ6TUtIMGgyMHpGNVF5aUkKLS0tIFZ1aERZb1FGUi95SEUwUEdBMnh2
            MmhkRHFZcytBVVhiaTdhSDRWckoySlUKui1bNuPTABi5RlOYwnb6PdEMjrnBPXcJ
            YUIs6FfoeBeKrQGo51+iIpewTTrh/uyX5nUkA2NZhMC399EXqknUKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T15:16:02Z"
    mac: ENC[AES256_GCM,data:xEvY5emEVf3ZbOOLEL7JUuEHGY0E5pWhFUyYI1e9zfhPXumrbaXSjN5xiCtl2ftqOXb4sPcAd+xFCjjSFn5IOgtnV72iIv3e/LU5fhKE4LpHVWFZWOfYC2FW8pIU7SAdqTWqgfO+rJw/gHO1jhxTGHbYtww4tPCBhQjug79V05I=,iv:wujp/UGGpQEWA5bnGoY0xjBr7qQQbCnsDajmRoDQyYA=,tag:Sfj9WtH2GrLlnfa+K/LbbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
