---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.0.20.254"
  METALLB_LB_RANGE: "10.0.20.200-10.0.20.220"
  METALLB_K8S_GATEWAY_ADDR: "10.0.20.200"
  METALLB_INGRESS_ADDR: "10.0.20.201"
