apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:RyLjZGEIk1Bf,iv:yRW6yEZgcJyZDsZbbiPuAgZbUumjySa0fn1Yoy1b6uU=,tag:s8sn2jiD8UCyfP07JYpk+g==,type:str]
    password: ENC[AES256_GCM,data:Ir403PHvJn5dlQeKnAW2R8MuTd+XT8rM6E/qyxfQOCI=,iv:55c6D+63WwUCZAmPY5RvDbSumb55+4UOZfSOlv+dmB4=,tag:TWguSrVWkFCUxJ6g6Bugzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQXhKWFBmeVF3UEhSQkFV
            Mks4UllZZ0YyVXRhL2JyTGlnRmF2dUxBdkh3CklYMkRxZ1prd04ydjNKWmxpZGVQ
            SG9vb0Z3dDBGRUk5aC9OOVBKRDJoZm8KLS0tIHFCYUNmMm9GQjA3T0VNZ3RrOG5m
            bmt2cXpaUlZYUTczUk9OeEFYSGlqbTAKvx5296A6FU4cSxxAX0lGPQVEoY22+MfG
            LP9KDMBOpWny3YQsEtKxjltPkx4aQ6qEt+QLqXYg/vOOVvZZ0MY6Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-12T17:54:29Z"
    mac: ENC[AES256_GCM,data:2cxTTU7ygmvo6hfs0fDYA8GQi+8+dEWofoUADVoOopLWm0PIvsDh7UAaV5W43NK9Vge1vwqMEUlHkWCmRl/+fWCO/EFOJmWGSja/+AQxo2wSgasTnpvQMyC0JbDo3ox/j8Wy7ID04dBvmhaX26hSGBu5Amb4WbuxY5MdNaggRb0=,iv:eKLd9IRe7IKB+YmoLjtx3MI/COGu+I5W1hK9KYIpKq0=,tag:xogNSsF2cJabZuUv2+Xa0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
