apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: storage
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:W9egZKXQ,iv:JuB+gFCn6chbCQcOi3HYZhY0nrC/Qevh+IljYzT4Wfk=,tag:08eBrqUV0WpLoowETxlRmA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7t+lHT1dvbHbHk6rKDfREyNCIQf6IEcjlYl5NpaScpU=,iv:RYy7EVwaRJpnBhu1hSwQT2QRVtnChhirAEAGMQS8wbc=,tag:dvayFDeDlqTC4tDnpXFbAA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:tHt3osvGtEUe4t5+FEw+Id2UOlSF7lIi/4i5+VS2ixmz,iv:uYFctwBgFk/or7cpEQIgjW6WlMo3mXfQdwG/YcnasUQ=,tag:8Fc2pY+BIN+4czpzkUxAmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT25Cd3d6enFXNStpZFVt
            ZE1PeGtjOEcxbmxuMWxINEJJNzBMS0R2SUY0CmJVYkxwdGlkQUszME02L2VkWGxu
            c3FDZ210eXBoVTFSK2R5SVVhUTM3aXMKLS0tIFljeDdQVUtnb2F5OXlhNXZIcUhJ
            WFhjcFhKeUNiL2lEYnhvZ2lmUFNiTGMKnXzBImpf/l5qkyxVt/2KtBnWaJuV8Wjb
            0FqDmcR0eYlyIb28jkfLZ3y6Ly9wNJUy//qljWmnvMHqoHyjfWNT/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-19T02:22:29Z"
    mac: ENC[AES256_GCM,data:LVfmR7rWeZz3R0uKkJjImHdS2LzH0NxWZGcy91srmXTH2BsiMSQRwS9Og/3YwXxibNsmfcK/mi0An6g+AV6sStYd79qON7jTw8sEdAUd3h52NHeWhrH39u5KdBmDZScbKzjDBnvnaa6hym7S51WLKLPxHkd7b2h09JhAI0o5WUY=,iv:hUwy4NtUR7bE6sQ3Z1AJhnNGZCOl4slUt88NJOMQ6uU=,tag:x9raVYbEWdxtPWYPbLm4PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
