apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: storage
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sz4z2Odc,iv:yHjN2MdwFMv+o8uHp8tsc9V/e2WWhJmPei4Fbqi1fi4=,tag:NzocEFQ5JIvJBabdTN2W7g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:y0dsUQX/lUUOImX3KF6uSAUSq3TX6dLeiUVV9UugSTk=,iv:RCDSV+TWx5ygn0j4hjdLZ8Vdkisj4bCvzuuk/ophFf0=,tag:29kAhLSbqB8gIougE4l3Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbFg3R04wNWlLZWk1VkZB
            azk2azZONGwwVVVRZzhZa2NEbjlOT3lHMGtFCjlncGVGV0ZockZiTmVnNWdLcWIz
            VzAyeUdpMW4zeG1ObDd5WkZIQ25UN00KLS0tIEszREFsRmZKQ3c2NURiandXZGlE
            Sm5VajZ3bi81S2x4WjY0ZmdHVzM0WHMKGP3r1aI0ebfWTw1cv4BDN5kUxpav1Lqe
            jUDDiY3c7p6anz+c0s7DfVJfLp0HsXHS4z1BCBkJ7PBGvFkXQtTUDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T23:48:45Z"
    mac: ENC[AES256_GCM,data:i7zTZ5OjfSi8LD2du3fI5PEskl4D2SoA4zuL7Wnizbn7Cfl8pwYrAIk3VzcWnEMHagfHLSDfCWtwDbv1VDvniDvsGYQsRBdvmlDLFBpqGRp54aPaFBvwGaQ1q3qDwkiALk8urlJu4iyciMpfCHE4vIUHCuWgMVerivnPimu3OOo=,iv:C0KAC8qBAnLbpee44au5E4rzBtCOyvAHOy8xV7mbmGs=,tag:WxLj2SA9LQ77hTGQwNWtZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
