apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:tnsWBzN8ltZGDQEsLw3lG7ruVN2E5XIAPxqIqsTcI9JSjaif,iv:hZJGR7l+19txxxOEPoqn1H+RplnVLB2Su8YQRb7y5JU=,tag:WZZwxJvPdxUJ9oQ3E/jmJw==,type:str]
    credentials.json: ENC[AES256_GCM,data:Dd8p+3RYoAg/yWu9XHo60SO4uXKOZ2+XkOSidjAE4CmFC/oJmtM8LDPqXs9wm46jG0PvPHU3YCyDSjxBCIQ5fZEV66aRzzg3RWmyFbDGalMfjDupW2cghWaWxkJCOC4ZKLXUle0WMMYmSGQY1xrEC11k1O3pVRCbviVfKwWaBOStaqmXs+9kzL3DpAIbeKidB/wNWXHhK7XxePBl/KIC4AWJv2u6I//qW75Q1F2LIA==,iv:ZPwLA4Ux9yX6VfRFl+Jm0hN32ZqT7cWYd/eCHrggNJc=,tag:XY+ys+pm9CU8ooe9ikQ8bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydDZwS2hPVWpjaU9mL0ov
            aEM3NVhTWFpKZnI2WTdYd29mRjIxN1ovOHdFCnFRTzVEV1d0QzZtY1VjM3VZRzhQ
            a2w3UEUybjlvaDEzZUxwTlJXWUhFOTQKLS0tIEVHTXVteUNPZnQ2NWhnS1pPU0t5
            UHRXTUNEN1RCaDZmVmFtMzBNWG5pVncKf+RL4tV33EMBSxPM6g96ESC5L55yGwhA
            /y2vuFvCJv7r8FAnIEBET5htPapHUaMVHX3ZtigIBaI5b/DeDS0uSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T01:38:47Z"
    mac: ENC[AES256_GCM,data:RhghO3NCfPA7oev3qwLn8u+IabGzT8VvhFw9mqVIy7kPH7C0aWiqrc9d+Je0nk27ajGMJ9CQimLs3cSVQrHudMKXc92Xvfknzp72+GZrPx3cQz0Pvpb/LTgV/zAmgdR7BvXDlKmy2MWR5g+v5b6bDGmAF1gAP+9UyVTXx0YYG44=,iv:Y5TR6mjuTbq1FBYhATh1eYu9SRvFbY00l2LHnS//+Vk=,tag:cqVGnvWOyyadFs5Zi0FeGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
