apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:OvZG20sp8xuKoqlS8YVc3zcxSdtYAn/nTNusbYuHDnm/HVc+,iv:qmn9ZsOOz4rknsMvdBsIr0dsShg1jAiw74lil/kEj24=,tag:upT3RUdTkSM648OwS32X+g==,type:str]
    credentials.json: ENC[AES256_GCM,data:n8hw1x/8NJ36+myFOEJETe9COSiM8vePigrMDtmOhuv4+peOcgBGuRERNpxGFXCDTKREVL9L9doBz/r/auHhTqdnnh9M2SzE61rXaV+R0ocOgiGQE2IxRVcgD9FYZT8IBFmrUSXQjbwsTN86IkO8+PeGjI+8zf3jpvk2Ufr4FT5Jy8bVKWZsnbIw9a72Kep7LOX3QtiUJPJK6P+q5ifTtK5svjLOffkmvYNOte137g==,iv:tzuNXSleek+Wp1fzLD88sXfLXGcCFBj+hHhmdUd546c=,tag:jcZR3aCyCTDwI7njX0u4kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXK3J2Y1lwbTdxVHBiL0Jh
            MDVFY0NlRUFVSW5tSWFqYWIrSkN3MlpoSFZNClliTXdUY29yeW9GZzB5U1EzazNU
            ZEsvN0FPY2g0K2QwZU5UMjBaeElwNFEKLS0tIG1aUXIzREtaRC9iNXFsUmJ4WVhk
            b0J4WjY2N1hERll5RmY5WGFCQXlZY1UKNw7qqHf1zgCwXHyCK/MF6DgTV+DvE+hD
            2xkNO2UUVK6OJ1qQtI6LFRn3c7OqFDG2BBPNs1woFps0zPeD7PqU9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T15:59:47Z"
    mac: ENC[AES256_GCM,data:AenIHAKyQ1qprv+X35dN6T/DtzRmK2I4vEenCVzzKPAVcQxFxJx3i2pfN3IST2cCtg73kpybS3l78g2g7LeqHfHmpMpkg8D9Yc2/d8sW+FUc8nJf1hEAz8hoIVN5BteacV60BWbXrKW1z06jQkhtq2Kbps2XhoVy0pRFOd7U6X0=,iv:829PoyXFgjYArwjh74hVYuTFNyZxa2L4hS1gPo37sAw=,tag:sBo85/5Ie/9TSiCz/K7J7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
