apiVersion: v1
kind: Secret
metadata:
    name: ext-posgres-operator-secret
    namespace: database
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:PQ068DinsaE=,iv:Zb1KugNeFw4+fn2h7ZLtfgcj7xVxtLiqqR6/J/Jd0to=,tag:KDUCluYj7faNlkGFFXuMvw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:+OJZrJGcR3k=,iv:hnTVBnJMSLo37LG+SWBsA0hV3OcSisC6nOvSDotgSE8=,tag:eAzk3bJjMxIzsWjouJTUNw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:GZ4FPUo/ifXs/s9+f8wMWQ==,iv:RCwO/yk02moClLR9DSHTeU+5MVktiwqkYtCIdlKRAJw=,tag:0ED+/kLH5n6v9u77NcXQqA==,type:str]
    POSTGRES_URI_ARGS: ""
    POSTGRES_CLOUD_PROVIDER: ""
    POSTGRES_DEFAULT_DATABASE: ENC[AES256_GCM,data:i1Q+2IfYWmE=,iv:KM2+u70Qp7tT6lX9SlSAIQiY3kLyCaRIQoMJl1lVV/s=,tag:R+HVNIFHk922x9meY6g5PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8fx8pmfgmsu8nxa26daqhf5kp2qu4cy8pcjqqjtednll828hy0quzn5wu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJckI2OXlicGxhS3o5bnRN
            MmJCakpWVWFDRVBYZk12T3J2RnNBNnI1WEJFClIzYWo5VmdTeWoyVVJaelBaNGw4
            cmFiaTlmUXpUOXhnL1hzTUFwNzZiWlEKLS0tIDJmMGhKb2FCWlJQSDRUNEdJQUd1
            MEdkOWsvMExGWEtLYWl1eFllZXhRU2sK06hbRJ9NU5iRODdv4Z/jZS+8IIBM1SHD
            Bj+5bu8eEFOh6cDnxDfeta9VOnL5xJ7gjyeJbNuTvdMS+BN6ZSnh9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T00:26:09Z"
    mac: ENC[AES256_GCM,data:GzpnWD1rLhr08hE1spWolAQdkIWthWw3RoojfPupAugsf+V30PLsAucoJB+NMfJrPaOfQ2Pew2QdGb2IzjKvUjETCZHSsk2ctMnanel1xSwrTNvHEo0V0VeV83ITt783SUvNTCCs5mBEeEIzv/6Y6lg35rnFwTkaB+in2nbdV3w=,iv:hkMipsJWwMlypTllOMbWBl1Eq20RqBqu6/SEO7/C4YE=,tag:6DFYb2GBet4rH67p3Skp9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
